# Generated by Django 4.2.8 on 2023-12-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_subscribed', models.BooleanField(default=True, verbose_name='Is subscribed')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Extra data')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletter',
                'ordering': ['-date', 'email'],
            },
        ),
    ]
