# Generated by Django 4.2.8 on 2023-12-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse électronique'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Données supplémentaires'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='is_subscribed',
            field=models.BooleanField(default=True, verbose_name='Inscrit'),
        ),
    ]
