# Generated by Django 4.2.8 on 2023-12-20 19:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='Sujet')),
                ('name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Nº de téléphone')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Répondu')),
                ('message', models.TextField(verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Données supplémentaires')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['is_answered', 'name', 'email', 'subject', 'date'],
            },
        ),
    ]
