# Generated by Django 4.2.8 on 2023-12-20 16:50

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('cover', models.ImageField(upload_to='blog/covers/%Y/', verbose_name='Couverture')),
                ('summary', models.TextField(help_text='Maximum 400 caractères', max_length=400, verbose_name='Résumé')),
                ('description', models.TextField(verbose_name='Contenu')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=8, verbose_name='Mots clés')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=500, null=True)),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='UUID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Données supplémentaires')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['-date', 'title', 'is_public'],
            },
        ),
    ]
