# Generated by Django 4.2.8 on 2023-12-20 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Contenu')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='UUID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='Publication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['user', 'post', '-date'],
            },
        ),
    ]
