# Generated by Django 4.2.8 on 2023-12-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Données supplémentaires'),
        ),
    ]
